### ISSUE TITLE
References to modules/instances?

### ISSUE THREAD

**Issue by lachlansneff** [WebAssembly/module-types#4]
Does this proposal extend to runtime-exposed module types? Or is it just standardizing a text format for module types?

Using module types, and being able to interface with known module type through a reference to an instance would be pretty cool. It'd be sort of like a class or trait.

**Comment by lukewagner** [comment]
[Originally](https://docs.google.com/presentation/d/11IIqttVbCsWtvhrmBcKMPdWqvEVdTE2nlvIzZMoOpyk/edit#slide=id.p), the only goal was just standardizing a text format.  But, coincidentally, I just opened a #3 about generalizing the proposal to do rather more at runtime (although really just loadtime).

**Comment by lachlansneff** [comment]
I'd love to see the ability have imported instances be more like dynamic references that can be built out of function references (and memory/table refs too) at runtime, but the other thread is probably the place to discuss it.
